dist: xenial
language: python
python:
  - "3.6"

cache:
  directories:
    - $HOME/.pip-cache/

# ignore the virtualenv that Travis creates
# setup a secure login to CodeCov
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - CODECOV_TOKEN="ffd8962e-2fa3-4e31-8101-f096c37284e1"

before_install:
  - gem install mdl
notifications:
  email: never

# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install --upgrade pipenv
  - pipenv install --dev
script:
  - shopt -s globstar
  - pipenv run pytest example/tests/test_termfrequency.py --cov-config pytest.cov --cov
  - pipenv run black **/*.py --check
  - pipenv run flake8 **/*.py
  - pipenv run pylint **/*.py
  - pipenv run pytest tests
  - mdl README.md

# report coverage information to CodeCov
after_success:
  - pipenv run codecov
